stages:
  - build
  - test
  - sast
  - docker-build
  - image-scan
  - deploy
  - security_scan_dynamic

build:
  image: python:3.10-slim
  stage: build
  script:
    - cd src/app
    - pip install -r requirements.txt
    - python -m py_compile app.py

test:
  image: python:3.10-slim
  stage: test
  script:
    - cd src/app
    - pip install -r requirements.txt
    - python app.py &
    - sleep 3
    - python -c "import urllib.request; print(urllib.request.urlopen('http://127.0.0.1:5000/health').read().decode())"

sonarqube-check:
  stage: sast
  tags:
    - shell
  before_script:
    # Lệnh PowerShell để kiểm tra và tạo mạng nếu chưa tồn tại
    - if (!(docker network ls --filter name=^devsecops_net$ -q)) { docker network create devsecops_net }
  script:
    - docker run --rm --network devsecops_net -v "${CI_PROJECT_DIR}:/usr/src" sonarsource/sonar-scanner-cli "-Dsonar.projectKey=devsecops-flask-web" "-Dsonar.sources=src/app" "-Dsonar.host.url=$SONAR_HOST_URL" "-Dsonar.login=$SONAR_TOKEN"
  allow_failure: true

bandit-sast:
  stage: sast
  image: python:3.10-slim
  script:
    - pip install bandit
    # Quét toàn bộ code trong src/app, xuất kết quả ra màn hình log
    - bandit -r src/app
  allow_failure: true

docker-build:
  image: docker:24
  stage: docker-build
  services:
    - docker:24-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" ./src/app
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

trivy-scan:
  stage: image-scan
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker run --rm aquasec/trivy:0.50.1 image --severity HIGH,CRITICAL "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

deploy-staging:
  stage: deploy
  tags:
    - shell
  script:
    - docker compose up -d web
    - echo "Deploy thành công"

run_dynamic_scan:
  stage: security_scan_dynamic
  tags:
    - shell
  before_script:
    - if (!(docker network ls --filter name=^devsecops_net$ -q)) { docker network create devsecops_net }
  script:
    - if (!(Test-Path "zap_reports")) { New-Item -ItemType Directory -Path "zap_reports" }
    - docker run --rm --network devsecops_net -v "${PWD}/zap_reports:/zap/wrk:rw" ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://192.168.5.227:5000 -r zap_report.html
  artifacts:
    when: always
    paths:
      - zap_reports/zap_report.html
  allow_failure: true