version: '3.8'



services:

  web:
    image: ${CI_REGISTRY_IMAGE:-devsecops-web-image}:${IMAGE_TAG:-latest}
    container_name: devsecops-web-container
    ports:
      - "5000:5000"
    networks:
      - devsecops_net
    volumes:
      - web_sqlite_data:/app/database.db

    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"



  sonarqube:

    image: sonarqube:lts-community

    container_name: devsecops-sonarqube

    ports:

      - "9000:9000"

    networks:

      - devsecops_net

    environment:

      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

    volumes:

      - sonarqube_data:/opt/sonarqube/data

      - sonarqube_extensions:/opt/sonarqube/extensions

      - sonarqube_logs:/opt/sonarqube/logs



volumes:

  sonarqube_data:

  sonarqube_extensions:

  sonarqube_logs:

  web_sqlite_data:

  
networks:

  devsecops_net:
    name: devsecops_net
    driver: bridge